# Config file for GFlows.
# See https://github.com/jbrunton/gflows/wiki/Configuration for options.
githubDir: ../../.github
templates:
  engine: jsonnet
  defaults:
    libs:
    - https://raw.githubusercontent.com/jbrunton/gflows/develop/e2e/gflowslibs/jsonnet/my-lib.gflowslib
