# Config file for GFlows.
# See https://github.com/jbrunton/gflows#configuration for options.
templates:
  engine: ytt
  defaults:
    libs:
      files:
        - workflows/common
        - workflows/config
