#@ load("workflows.lib.yml", "pull_request_defaults")
#@ load("steps.lib.yml", "setup_go")

name: gflows

"on": #@ pull_request_defaults()

jobs:
  check_workflows:
    name: check-workflows [ex-default-ytt-gflows]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - #@ setup_go()
    - uses: jbrunton/setup-gflows@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: validate workflows
      env:
        GFLOWS_CONFIG: .gflows/examples/default-ytt/config.yml
      run: gflows check
