#@ load("workflows.lib.yml", "pull_request_defaults")
#@ load("steps.lib.yml", "setup_gflows", "check_workflows")

name: gflows

"on": #@ pull_request_defaults()

jobs:
  check_workflows:
    name: check-workflows [ex-default-ytt-gflows]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - #@ setup_gflows()
    - #@ check_workflows()
