#@ load("workflows.lib.yml", "pull_request_defaults")

name: gflows

"on": #@ pull_request_defaults()

jobs:
  check_workflows:
    name: check-workflows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: "^1.14.4"
    - name: install gflows
      run: go get github.com/jbrunton/gflows
    - name: validate workflows
      run: gflows check
